--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : Saturday, 06 December, 2014 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 
USE Mitra
;

--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.FK_id_entidade_social') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AssistenciaSocial.Beneficiario DROP CONSTRAINT FK_id_entidade_social
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.FK_id_tipo_assistencia') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AssistenciaSocial.Beneficiario DROP CONSTRAINT FK_id_tipo_assistencia
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.FK_id_beneficiario') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AssistenciaSocial.Dependente DROP CONSTRAINT FK_id_beneficiario
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.FK_id_beneficiario') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE AssistenciaSocial.Filiacao DROP CONSTRAINT FK_id_beneficiario
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.Beneficiario') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AssistenciaSocial.Beneficiario
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.Dependente') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AssistenciaSocial.Dependente
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.EntidadeSocial') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AssistenciaSocial.EntidadeSocial
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.Filiacao') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AssistenciaSocial.Filiacao
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('AssistenciaSocial.TipoDeAssistencia') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE AssistenciaSocial.TipoDeAssistencia
;


--  Create Tables 
CREATE TABLE AssistenciaSocial.Beneficiario ( 
	Id int identity(1,1)  NOT NULL,
	id_tipo_assistencia int,
	id_entidade_social int,
	Nome varchar(100),
	CPF varchar(15),
	RG varchar(20),
	DataDeNascimento date,
	Sexo char(1),
	EstadoCivil char(1),
	Naturalidade varchar(50),
	Cor char(1),
	GrauDeInstrucao char(1),
	Endereco varchar(255),
	Bairro varchar(50),
	Cidade varchar(100),
	Estado char(2),
	Telefone varchar(15),
	PontoDeFerencia varchar(max),
	NomeDoResponsavel varchar(100),
	TelefoneDoResponsavel varchar(15),
	RendaFamiliar char(1),
	BeneficioDeEntidade bit,
	TipoDeBeneficioDaEntidade varchar(max),
	NomeDaEntidade varchar(255),
	TipoDeResidencia char(1),
	EspecificarTipoDeResidencia varchar(max),
	TipoDeConstrucao char(1),
	PisoDaConstrucao char(1),
	CoberturaDaConstrucao char(1),
	NumeroDeComodosDaConstrucao smallint,
	ComodosDaConstrucao varchar(max),
	EsgotoDaConstrucao char(1),
	AguaDaConstrucao char(1),
	BanheiroDaConstrucao char(1),
	EnergiaEletricaDaConstrucao char(1),
	LixoDaConstrucao char(1),
	PossuiOutrosImoveis bit,
	TipoDeConstrucaoOutrosImoveis char(1),
	PossuiVeiculo bit,
	UtilizacaoDoVeiculo char(1),
	AnoDoVeiculo int,
	ModeloDoVeiculo varchar(50),
	PossuiConvenioMedico bit,
	NomeDoConvenioMedico varchar(50),
	TratamentoMedico varchar(max),
	QualTipoDeDoenca varchar(100),
	MedicamentoDeUsoContinuo varchar(255),
	ComoAdquireMedicamentos char(1),
	EspecificarComoAdquireMedicamentos varchar(max),
	InformacoesAdicionais varchar(max),
	DataDeCadastro datetime DEFAULT (GetDate())
)
;

CREATE TABLE AssistenciaSocial.Dependente ( 
	Id int identity(1,1)  NOT NULL,
	id_beneficiario int,
	Nome varchar(100),
	DataDeNascimento date,
	Parentesco char(1),
	EstadoCivil char(1),
	GrauDeInstrucao char(1),
	Profissao varchar(100)
)
;

CREATE TABLE AssistenciaSocial.EntidadeSocial ( 
	Id int identity(1,1)  NOT NULL,
	Nome varchar(255),
	Endereco varchar(255),
	Telefone varchar(15),
	CNPJ varchar(50)
)
;

CREATE TABLE AssistenciaSocial.Filiacao ( 
	Parentesco char(1) NOT NULL,
	id_beneficiario int NOT NULL,
	Nome varchar(100),
	EstadoCivil char(1),
	DataDeNascimento date,
	GrauDeInstrucao char(1),
	LocalDeTrabalho varchar(100),
	EnderecoDeTrabalho varchar(255),
	Telefone varchar(15),
	Profissao varchar(100),
	FaixaSalarial varchar(50),
	HorarioDeTrabalho char(1)
)
;

CREATE TABLE AssistenciaSocial.TipoDeAssistencia ( 
	Id int identity(1,1)  NOT NULL,
	Descricao varchar(255)
)
;


--  Create Primary Key Constraints 
ALTER TABLE AssistenciaSocial.Beneficiario ADD CONSTRAINT PK_Beneficiario 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE AssistenciaSocial.Dependente ADD CONSTRAINT PK_Dependente 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE AssistenciaSocial.EntidadeSocial ADD CONSTRAINT PK_EntidadeSocial 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE AssistenciaSocial.Filiacao ADD CONSTRAINT PK_Filiacao 
	PRIMARY KEY CLUSTERED (Parentesco, id_beneficiario)
;

ALTER TABLE AssistenciaSocial.TipoDeAssistencia ADD CONSTRAINT PK_TipoDeAssistencia 
	PRIMARY KEY CLUSTERED (Id)
;